import { SceneModel } from './scene.model';

export const SCENES : SceneModel[] = [
  new SceneModel('cheddar tavern', 'you enter a tavern faintly smelling of aged gouda, the bar tender obviously comprised of swiss and havarti, greets you with a crooked grin. He asks you for help with the munster menace!', ['tell the barkeep to cheese off!', 'munster menace? how can I help the kurd Kingdom?!'], 1),
  new SceneModel('Outside of the Cheddar Tavern', 'After telling off that stupid barkeep you head outside for a snack (cheese sticks, obviously), and you immeadeatly run into a pack of howling Pecorino Wolf! What do you do?' ['Fight the Pecorino off! Attack with your trusty {{this.weapon}}', 'RUN AWWWWAY, like the pile of cottage cheese you are.'], 2),
  new SceneModel('The Basement of the Cheddar Tavern', 'the wonderful barkeep asks you to check out the basement, because there is a few annoying blue cheese spiders down there that he needs help with, He also mentions that the last person he asked for help, Prince Camembert, has not returned...In the basement you see string cheese hanging from the rafters and some hissing from below, you see a few of the noted spiders and prepare your {{this.weapon}}', ['Attack those filthy blue cheese spiders', 'Use the strign cheese to tie them together, and eatthem with a nice Pinot and your favorite baguette'],3),
  new SceneModel('The Basement of the Cheddar Tavern', 'After soundly defeating/eating the (tasty?) spiders, you see the the the moldy Prince Camembert in the dark corner of the room', ['Search the Prince\'s corpse', 'leave the basement through a side door'], 4),
  new SceneModel('The Swiss Cheese Tunnels', 'After searching the Prince\'s corpse, you find a torch and a map that was meant to lead him into the dark and dank tunnels. Upon entering you hear a far off grinding of stone upon stone, before you there is a fork in the tunnel. one lit and one dark', ['take the lit corridor and save your torch for later', 'take the dark tunnel and use your torch'], 5),
  new SceneModel('Troll Truckle', '(thud)...(thud)...(thud)...(crunch)...(O.o) the scraping sound now becomes clear as you see a monsterous Roquefort Troll dragging a stone hammer', ['fight the troll with your {{this.weapon}}', 'attack the troll with the torch in your hands'], 6),
  new SceneModel('The Great Mozzarella Chasm', 'You approach a large chasm, known for the great MOzzarella river that flows beneath. You see a light onthe other side of chasm but first you must try and cross a very rickety bridge.' ['Cross the bridge', 'Head back from whence you came.'], 7),
  new SceneModel('Cheese-Wheel House', 'You enter the Cheese-Wheel House, and there are three doors.', [ 'The Door of Limb-burger', 'The Door of Velbleeda', 'The Door of Mas-corspe-one'], 8),
  new SceneModel('The Room of Limb-burger', 'As you open the door of Limb-burger, you take a deeeeeeeeeeeeep breathe of the world\'s smelliest cheese, and you quickly and painfully succumb to death', ['Looks like i died, tell mom i loved her', 'I always hated cheese'], 9),
  new SceneModel('The Room of Mas-corspe-one', 'As you enter, the thick stench of brie smacks you in the nose holes, "GOOD GOD," you curse all the 17 cheese gods. Through your watering eyes, you make out an amorphous brie-blob', ['attack the brieast with {{this.weapon}}','attack the beast with {{this.goodWeapon}}', 'light and throw your torch at the brieast'], 10),
  new SceneModel('The Room of Velbleeda', 'As you slowly enter the rather large room , you see a gigantic creature apprach which seems to be an amalgamation of Swiss, Munster, Kraft American Singles and hard scales made of Tostitos scoops. As you edge away, this Munster Monster shoots a blob out of his maw in the form of half eaten, molten hot velveeta and shells.', ['Attack with {{this.goodWeapon}}', 'Attack with {{this.weapon}}', 'Throw lit torch at the Munster Monster', 'Take out a fork and try and eat some of the velveeta. WHAT I\'M HUNGRY!'], 11),
  new SceneModel('VICTORY', 'You have slain the Munster Monster and saved all of the 7 familes of the Kurd Kingdoms.', ['You won. Yay. Play again', 'I won? Ok. I\'ll play again..'], 12),
  new SceneModel("Treasure Room", "After slaying the Roquefort Troll, you find a treasure cheat filled with valuble jewels and weapons.", ["Take the jewels and riches and continue on outside of the room", "Take the weapon and continue on outside of the room."], 13),
  new SceneModel('DEEEEAAATHH BY CHEEEEZZZZEEE', 'You have bitten of more cheese than you can chew. It is the end...... or is it?', ['play again'], 14)
];
